// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reset_token.sql

package db

import (
	"context"
	"time"
)

const createResetToken = `-- name: CreateResetToken :one
INSERT INTO
    reset_tokens (user_id, token, expiry_date)
VALUES ($1, $2, $3)
RETURNING
    user_id,
    token,
    expiry_date
`

type CreateResetTokenParams struct {
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}

type CreateResetTokenRow struct {
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}

func (q *Queries) CreateResetToken(ctx context.Context, arg CreateResetTokenParams) (*CreateResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createResetToken, arg.UserID, arg.Token, arg.ExpiryDate)
	var i CreateResetTokenRow
	err := row.Scan(&i.UserID, &i.Token, &i.ExpiryDate)
	return &i, err
}

const deleteResetToken = `-- name: DeleteResetToken :exec
DELETE FROM reset_tokens WHERE user_id = $1
`

func (q *Queries) DeleteResetToken(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteResetToken, userID)
	return err
}

const getResetToken = `-- name: GetResetToken :one
SELECT user_id, token, expiry_date
FROM reset_tokens
WHERE
    token = $1
`

type GetResetTokenRow struct {
	UserID     int64     `json:"user_id"`
	Token      string    `json:"token"`
	ExpiryDate time.Time `json:"expiry_date"`
}

func (q *Queries) GetResetToken(ctx context.Context, token string) (*GetResetTokenRow, error) {
	row := q.db.QueryRow(ctx, getResetToken, token)
	var i GetResetTokenRow
	err := row.Scan(&i.UserID, &i.Token, &i.ExpiryDate)
	return &i, err
}
