// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: transaction/transaction_command.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApiKey          string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CardNumber      string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount          int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                  `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transaction_transaction_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateTransactionRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateTransactionRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

type UpdateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int32                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ApiKey          string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CardNumber      string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount          int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                  `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_transaction_transaction_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTransactionRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateTransactionRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateTransactionRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

type ApiResponseTransactionDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionDelete) Reset() {
	*x = ApiResponseTransactionDelete{}
	mi := &file_transaction_transaction_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionDelete) ProtoMessage() {}

func (x *ApiResponseTransactionDelete) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionDelete) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_command_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseTransactionDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseTransactionAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionAll) Reset() {
	*x = ApiResponseTransactionAll{}
	mi := &file_transaction_transaction_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionAll) ProtoMessage() {}

func (x *ApiResponseTransactionAll) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_transaction_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionAll.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionAll) Descriptor() ([]byte, []int) {
	return file_transaction_transaction_command_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseTransactionAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transaction_transaction_command_proto protoreflect.FileDescriptor

const file_transaction_transaction_command_proto_rawDesc = "" +
	"\n" +
	"%transaction/transaction_command.proto\x12\x0epb.transaction\x1a\x1dtransaction/transaction.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x01\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x05R\n" +
	"merchantId\x12E\n" +
	"\x10transaction_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\"\xa2\x02\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x05R\rtransactionId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x05R\n" +
	"merchantId\x12E\n" +
	"\x10transaction_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\"P\n" +
	"\x1cApiResponseTransactionDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x19ApiResponseTransactionAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x89\x06\n" +
	"\x19TransactionCommandService\x12e\n" +
	"\x11CreateTransaction\x12(.pb.transaction.CreateTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12e\n" +
	"\x11UpdateTransaction\x12(.pb.transaction.UpdateTransactionRequest\x1a&.pb.transaction.ApiResponseTransaction\x12p\n" +
	"\x12TrashedTransaction\x12*.pb.transaction.FindByIdTransactionRequest\x1a..pb.transaction.ApiResponseTransactionDeleteAt\x12p\n" +
	"\x12RestoreTransaction\x12*.pb.transaction.FindByIdTransactionRequest\x1a..pb.transaction.ApiResponseTransactionDeleteAt\x12v\n" +
	"\x1aDeleteTransactionPermanent\x12*.pb.transaction.FindByIdTransactionRequest\x1a,.pb.transaction.ApiResponseTransactionDelete\x12\\\n" +
	"\x15RestoreAllTransaction\x12\x16.google.protobuf.Empty\x1a).pb.transaction.ApiResponseTransactionAll\"\x00\x12d\n" +
	"\x1dDeleteAllTransactionPermanent\x12\x16.google.protobuf.Empty\x1a).pb.transaction.ApiResponseTransactionAll\"\x00B?Z=github.com/MamangRust/monolith-payment-gateway-pb/transactionb\x06proto3"

var (
	file_transaction_transaction_command_proto_rawDescOnce sync.Once
	file_transaction_transaction_command_proto_rawDescData []byte
)

func file_transaction_transaction_command_proto_rawDescGZIP() []byte {
	file_transaction_transaction_command_proto_rawDescOnce.Do(func() {
		file_transaction_transaction_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_transaction_command_proto_rawDesc), len(file_transaction_transaction_command_proto_rawDesc)))
	})
	return file_transaction_transaction_command_proto_rawDescData
}

var file_transaction_transaction_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_transaction_transaction_command_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),       // 0: pb.transaction.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),       // 1: pb.transaction.UpdateTransactionRequest
	(*ApiResponseTransactionDelete)(nil),   // 2: pb.transaction.ApiResponseTransactionDelete
	(*ApiResponseTransactionAll)(nil),      // 3: pb.transaction.ApiResponseTransactionAll
	(*timestamppb.Timestamp)(nil),          // 4: google.protobuf.Timestamp
	(*FindByIdTransactionRequest)(nil),     // 5: pb.transaction.FindByIdTransactionRequest
	(*emptypb.Empty)(nil),                  // 6: google.protobuf.Empty
	(*ApiResponseTransaction)(nil),         // 7: pb.transaction.ApiResponseTransaction
	(*ApiResponseTransactionDeleteAt)(nil), // 8: pb.transaction.ApiResponseTransactionDeleteAt
}
var file_transaction_transaction_command_proto_depIdxs = []int32{
	4, // 0: pb.transaction.CreateTransactionRequest.transaction_time:type_name -> google.protobuf.Timestamp
	4, // 1: pb.transaction.UpdateTransactionRequest.transaction_time:type_name -> google.protobuf.Timestamp
	0, // 2: pb.transaction.TransactionCommandService.CreateTransaction:input_type -> pb.transaction.CreateTransactionRequest
	1, // 3: pb.transaction.TransactionCommandService.UpdateTransaction:input_type -> pb.transaction.UpdateTransactionRequest
	5, // 4: pb.transaction.TransactionCommandService.TrashedTransaction:input_type -> pb.transaction.FindByIdTransactionRequest
	5, // 5: pb.transaction.TransactionCommandService.RestoreTransaction:input_type -> pb.transaction.FindByIdTransactionRequest
	5, // 6: pb.transaction.TransactionCommandService.DeleteTransactionPermanent:input_type -> pb.transaction.FindByIdTransactionRequest
	6, // 7: pb.transaction.TransactionCommandService.RestoreAllTransaction:input_type -> google.protobuf.Empty
	6, // 8: pb.transaction.TransactionCommandService.DeleteAllTransactionPermanent:input_type -> google.protobuf.Empty
	7, // 9: pb.transaction.TransactionCommandService.CreateTransaction:output_type -> pb.transaction.ApiResponseTransaction
	7, // 10: pb.transaction.TransactionCommandService.UpdateTransaction:output_type -> pb.transaction.ApiResponseTransaction
	8, // 11: pb.transaction.TransactionCommandService.TrashedTransaction:output_type -> pb.transaction.ApiResponseTransactionDeleteAt
	8, // 12: pb.transaction.TransactionCommandService.RestoreTransaction:output_type -> pb.transaction.ApiResponseTransactionDeleteAt
	2, // 13: pb.transaction.TransactionCommandService.DeleteTransactionPermanent:output_type -> pb.transaction.ApiResponseTransactionDelete
	3, // 14: pb.transaction.TransactionCommandService.RestoreAllTransaction:output_type -> pb.transaction.ApiResponseTransactionAll
	3, // 15: pb.transaction.TransactionCommandService.DeleteAllTransactionPermanent:output_type -> pb.transaction.ApiResponseTransactionAll
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_transaction_transaction_command_proto_init() }
func file_transaction_transaction_command_proto_init() {
	if File_transaction_transaction_command_proto != nil {
		return
	}
	file_transaction_transaction_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_transaction_command_proto_rawDesc), len(file_transaction_transaction_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_transaction_command_proto_goTypes,
		DependencyIndexes: file_transaction_transaction_command_proto_depIdxs,
		MessageInfos:      file_transaction_transaction_command_proto_msgTypes,
	}.Build()
	File_transaction_transaction_command_proto = out.File
	file_transaction_transaction_command_proto_goTypes = nil
	file_transaction_transaction_command_proto_depIdxs = nil
}
