global:
  scrape_interval: 10s
  evaluation_interval: 10s


alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - rules/golang-runtime-alerts.yaml
  - rules/kafka-exporter-alerts.yaml
  - rules/node-exporter-alerts.yaml
  - rules/otel-collector-alerts.yaml
  - rules/apigateway-alerts.yaml
  - rules/auth-service-alerts.yaml
  - rules/card-service-alerts.yaml
  - rules/email-service-alerts.yaml
  - rules/merchant-service-alerts.yaml
  - rules/role-service-alerts.yaml
  - rules/saldo-service-alerts.yaml
  - rules/topup-service-alerts.yaml
  - rules/transaction-service-alerts.yaml
  - rules/transfer-service-alerts.yaml
  - rules/user-service-alerts.yaml
  - rules/withdrawal-service-alerts.yaml

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          application: 'Otel Collector'
          environment: 'production'
  
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          application: 'Kafka Exporter'
          environment: 'production'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          application: 'Node Exporter'
          environment: 'production'

  - job_name: 'apigateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apigateway:8091']
        labels:
          application: 'API Gateway'
          environment: 'production'

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth:8081']
        labels:
          application: 'Auth Service'
          environment: 'production'

  - job_name: 'merchant-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['merchant:8084']
        labels:
          application: 'Merchant Service'
          environment: 'production'

  - job_name: 'card-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['card:8083']
        labels:
          application: 'Card Service'
          environment: 'production'


  - job_name: 'saldo-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['saldo:8086']
        labels:
          application: 'Saldo Service'
          environment: 'production'


  - job_name: 'role-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['role:8082']
        labels:
          application: 'Role Service'
          environment: 'production'


  - job_name: 'topup-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['topup:8087']
        labels:
          application: 'Topup Service'
          environment: 'production'

  - job_name: 'transaction-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transaction:8088']
        labels:
          application: 'Transaction Service'
          environment: 'production'

  - job_name: 'transfer-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transfer:8089']
        labels:
          application: 'Transfer Service'
          environment: 'production'

  - job_name: 'user-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['user:8085']
        labels:
          application: 'User Service'
          environment: 'production'

  - job_name: 'email-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['email:8080']
        labels:
          application: 'Email Service'
          environment: 'production'


  - job_name: 'withdraw-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['withdraw:8090']
        labels:
          application: 'Withdraw Service'
          environment: 'production'
