FROM golang:1.25.7-bookworm AS builder

WORKDIR /app

# Copy dependency manifests first (cache friendly)
COPY shared/go.mod shared/go.sum ./shared/
COPY pkg/go.mod pkg/go.sum ./pkg/
COPY pb/go.mod pb/go.sum ./pb/
# Copy all service go.mod files because they are inter-dependent
COPY service/ ./service/
RUN find service -type f ! -name "go.mod" ! -name "go.sum" -delete

# Copy workspace configuration
COPY go.work ./

WORKDIR /app/service/auth

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

WORKDIR /app

# Copy source
COPY shared/ ./shared/
COPY pkg/ ./pkg/
COPY pb/ ./pb/
COPY service/ ./service/

WORKDIR /app/service/auth

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/auth_bin ./cmd/main.go


FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN addgroup -g 1000 appuser && \
    adduser -D -s /bin/sh -u 1000 -G appuser appuser

WORKDIR /app

RUN mkdir -p /var/log/app && chown -R 1000:1000 /var/log/app

COPY --from=builder /app/auth_bin ./auth

RUN chown -R 1000:1000 ./auth 

USER appuser

EXPOSE 50051

CMD ["./auth"]
