apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: apigateway:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: app-config
