apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: payment-gateway
spec:
  selector:
    app: auth-service
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP

