apiVersion: apps/v1
kind: Deployment
metadata:
  name: card
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: card
  template:
    metadata:
      labels:
        app: card
    spec:
      containers:
      - name: card
        image: card-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
