apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-service
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: card-service
  template:
    metadata:
      labels:
        app: card-service
    spec:
      containers:
      - name: card-service
        image: card-service:1.0
        ports:
        - containerPort: 50053
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: app-config
