apiVersion: v1
kind: Service
metadata:
  name: card-service
  namespace: payment-gateway
spec:
  selector:
    app: card-service
  ports:
  - name: grpc
    port: 50053
    targetPort: 50053
  - name: http
    port: 8083
    targetPort: 8083
  type: ClusterIP