apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: payment-gateway
data:
  APP_ENV: "kubernetes"
  DB_DRIVER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "PAYMENT_GATEWAY"

  POSTGRES_DB: "PAYMENT_GATEWAY"

  DB_MAX_OPEN_CONNS: "50"
  DB_MAX_IDLE_CONNS: "10"
  DB_CONN_MAX_LIFETIME: "30m"

  DB_SEEDER: "true"
  APP_LOGGER: "production"

  KAFKA_BROKERS: "kafka.payment-gateway.svc.cluster.local:9092"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  REDIS_DB_AUTH: "0"
  REDIS_DB_ROLE: "1"
  REDIS_DB_USER: "2"
  REDIS_DB_CARD: "3"
  REDIS_DB_MERCHANT: "4"
  REDIS_DB_TRANSACTION: "5"
  REDIS_DB_SALDO: "6"
  REDIS_DB_TOPUP: "7"
  REDIS_DB_TRANSFER: "8"
  REDIS_DB_WITHDRAW: "9"

  OTEL_ENDPOINT: "otel-collector.payment-gateway.svc.cluster.local:4317"

  GRPC_AUTH_ADDR: "auth.payment-gateway.svc.cluster.local:50051"
  GRPC_ROLE_ADDR: "role.payment-gateway.svc.cluster.local:50052"
  GRPC_CARD_ADDR: "card.payment-gateway.svc.cluster.local:50053"
  GRPC_MERCHANT_ADDR: "merchan.payment-gateway.svc.cluster.local:50054"
  GRPC_USER_ADDR: "user.payment-gateway.svc.cluster.local:50055"
  GRPC_SALDO_ADDR: "saldo.payment-gateway.svc.cluster.local:50056"
  GRPC_TOPUP_ADDR: "topup.payment-gateway.svc.cluster.local:50057"
  GRPC_TRANSACTION_ADDR: "transaction.payment-gateway.svc.cluster.local:50058"
  GRPC_TRANSFER_ADDR: "transfer.payment-gateway.svc.cluster.local:50059"
  GRPC_WITHDRAW_ADDR: "withdraw.payment-gateway.svc.cluster.local:50060"

  GRPC_AUTH_PORT: "50051"
  GRPC_ROLE_PORT: "50052"
  GRPC_CARD_PORT: "50053"
  GRPC_MERCHANT_PORT: "50054"
  GRPC_USER_PORT: "50055"
  GRPC_SALDO_PORT: "50056"
  GRPC_TOPUP_PORT: "50057"
  GRPC_TRANSACTION_PORT: "50058"
  GRPC_TRANSFER_PORT: "50059"
  GRPC_WITHDRAW_PORT: "50060"

  METRIC_EMAIL_ADDR: "8080"
  METRIC_AUTH_ADDR: "8081"
  METRIC_ROLE_ADDR: "8082"
  METRIC_CARD_ADDR: "8083"
  METRIC_MERCHANT_ADDR: "8084"
  METRIC_USER_ADDR: "8085"
  METRIC_SALDO_ADDR: "8086"
  METRIC_TOPUP_ADDR: "8087"
  METRIC_TRANSACTION_ADDR: "8088"
  METRIC_TRANSFER_ADDR: "8089"
  METRIC_WITHDRAW_ADDR: "8090"
