apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: email-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
