apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: payment-gateway
spec:
  selector:
    app: jaeger
  ports:
  - name: udp
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: ui
    port: 16686
    targetPort: 16686
  type: LoadBalancer