apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.62.0
        ports:
        - containerPort: 6831
          protocol: UDP
        - containerPort: 16686
