apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:v1.9.0
        command:
        - --kafka.server=kafka:9092
        - --web.listen-address=0.0.0.0:9308
        - --log.level=debug
        ports:
        - containerPort: 9308
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9308
          initialDelaySeconds: 30
          periodSeconds: 30
