apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter-service
  namespace: payment-gateway
spec:
  selector:
    app: kafka-exporter
  ports:
  - port: 9308
    targetPort: 9308
  type: ClusterIP
