apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-logs-pvc
  namespace: payment-gateway
spec:
  accessModes:
    - ReadWriteOnce              
  resources:
    requests:
      storage: 5Gi               
  storageClassName: standard     
  volumeName: app-logs-pv       
