apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-logs-pv
  namespace: payment-gateway
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: logs-storage
  hostPath:
    path: /data/logs