apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-data-pv
  namespace: payment-gateway
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/loki