apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: merchant
  template:
    metadata:
      labels:
        app: merchant
    spec:
      containers:
      - name: merchant
        image: merchant-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
