apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-service
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-service
  template:
    metadata:
      labels:
        app: merchant-service
    spec:
      containers:
      - name: merchant-service
        image: merchant-service:1.0
        ports:
        - containerPort: 50054
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: app-config