apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: payment-gateway
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: migrate-service:1.1
          workingDir: /app
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
