apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: payment-gateway
data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

      jaeger:
        protocols:
          grpc:
            endpoint: 0.0.0.0:14250
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
          thrift_http:
            endpoint: 0.0.0.0:14268

      prometheus:
        config:
          scrape_configs:
            - job_name: "otel-collector"
              scrape_interval: 5s
              static_configs:
                - targets: ["localhost:8888"]
            - job_name: "movie-service"
              scrape_interval: 15s
              static_configs:
                - targets: ["server:8080"]
                  labels:
                    application: "movie-grpc-service"

    processors:
      batch:

    exporters:
      jaeger:
        endpoint: jaeger-service:14250
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
      otlp:
        endpoint: otelcol:4317

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [batch]
          exporters: [otlp, jaeger]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [otlp, prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
