apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          ports:
            - containerPort: 6432
          volumeMounts:
            - name: config-volume
              mountPath: /etc/pgbouncer
          readinessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: pgbouncer-config
                  items:
                    - key: pgbouncer.ini
                      path: pgbouncer.ini
              - secret:
                  name: pgbouncer-secret
                  items:
                    - key: userlist.txt
                      path: userlist.txt
