apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-service
  namespace: payment-gateway
spec:
  selector:
    app: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
  type: ClusterIP
