apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: payment-gateway
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
      - targets: ['node-exporter:9100']
    - job_name: 'kafka-exporter'
      static_configs:
      - targets: ['kafka-exporter:9308']
