apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4
        command:
        - redis-server
        - --requirepass
        - dragon_knight
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
