apiVersion: apps/v1
kind: Deployment
metadata:
  name: role
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: role
  template:
    metadata:
      labels:
        app: role
    spec:
      containers:
      - name: role
        image: role-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
