apiVersion: v1
kind: Service
metadata:
  name: role-service
  namespace: payment-gateway
spec:
  selector:
    app: role-service
  ports:
  - name: grpc
    port: 50052
    targetPort: 50052
  - name: http
    port: 8082
    targetPort: 8082
  type: ClusterIP

