apiVersion: v1
kind: Service
metadata:
  name: saldo
  namespace: payment-gateway
spec:
  selector:
    app: saldo
  ports:
    - name: http-metrics
      port: 8086
      targetPort: 8086
    - name: grpc
      port: 50056
      targetPort: 50056
  type: ClusterIP
