apiVersion: v1
kind: Service
metadata:
  name: saldo-service
  namespace: payment-gateway
spec:
  selector:
    app: saldo-service
  ports:
  - name: grpc
    port: 50056
    targetPort: 50056
  - name: http
    port: 8086
    targetPort: 8086
  type: ClusterIP