apiVersion: apps/v1
kind: Deployment
metadata:
  name: saldo
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saldo
  template:
    metadata:
      labels:
        app: saldo
    spec:
      containers:
      - name: saldo
        image: saldo-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
