apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: payment-gateway
type: Opaque
data:
  POSTGRES_PASSWORD: RFJBR09O
  REDIS_PASSWORD: ZHJhZ29uX2tuaWdodA==
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4=
