apiVersion: v1
kind: Service
metadata:
  name: topup
  namespace: payment-gateway
spec:
  selector:
    app: topup
  ports:
    - name: http-metrics
      port: 8087
      targetPort: 8087
    - name: grpc
      port: 50057
      targetPort: 50057
  type: ClusterIP
