apiVersion: v1
kind: Service
metadata:
  name: topup-service
  namespace: payment-gateway
spec:
  selector:
    app: topup-service
  ports:
  - name: grpc
    port: 50057
    targetPort: 50057
  - name: http
    port: 8087
    targetPort: 8087
  type: ClusterIP