apiVersion: apps/v1
kind: Deployment
metadata:
  name: topup
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: topup
  template:
    metadata:
      labels:
        app: topup
    spec:
      containers:
      - name: topup
        image: topup-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
