apiVersion: v1
kind: Service
metadata:
  name: transfer-service
  namespace: payment-gateway
spec:
  selector:
    app: transfer-service
  ports:
  - name: grpc
    port: 50059
    targetPort: 50059
  - name: http
    port: 8089
    targetPort: 8089
  type: ClusterIP