apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-service
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
      - name: transfer-service
        image: transfer-service:1.0
        ports:
        - containerPort: 50059
        - containerPort: 8089
        envFrom:
        - configMapRef:
            name: app-config