apiVersion: v1
kind: Service
metadata:
  name: transfer
  namespace: payment-gateway
spec:
  selector:
    app: transfer
  ports:
    - name: http-metrics
      port: 8089
      targetPort: 8089
    - name: grpc
      port: 50059
      targetPort: 50059
  type: ClusterIP
