apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: payment-gateway
spec:
  selector:
    app: transaction-service
  ports:
  - name: grpc
    port: 50058
    targetPort: 50058
  - name: http
    port: 8088
    targetPort: 8088
  type: ClusterIP