apiVersion: v1
kind: Service
metadata:
  name: transaction
  namespace: payment-gateway
spec:
  selector:
    app: transaction
  ports:
    - name: http-metrics
      port: 8088
      targetPort: 8088
    - name: grpc
      port: 50058
      targetPort: 50058
  type: ClusterIP
