apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: payment-gateway
spec:
  selector:
    app: user
  ports:
    - name: http-metrics
      port: 8085
      targetPort: 8085
    - name: grpc
      port: 50055
      targetPort: 50055
  type: ClusterIP
