apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: payment-gateway
spec:
  selector:
    app: user-service
  ports:
  - name: grpc
    port: 50055
    targetPort: 50055
  - name: http
    port: 8085
    targetPort: 8085
  type: ClusterIP
