apiVersion: apps/v1
kind: Deployment
metadata:
  name: withdraw
  namespace: payment-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: withdraw
  template:
    metadata:
      labels:
        app: withdraw
    spec:
      containers:
      - name: withdraw
        image: withdraw-service:1.0
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        ports:
        - containerPort: 8080
