apiVersion: v1
kind: Service
metadata:
  name: withdraw-service
  namespace: payment-gateway
spec:
  selector:
    app: withdraw-service
  ports:
  - name: grpc
    port: 50060
    targetPort: 50060
  - name: http
    port: 8090
    targetPort: 8090
  type: ClusterIP