apiVersion: apps/v1
kind: Deployment
metadata:
  name: withdraw-service
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: withdraw-service
  template:
    metadata:
      labels:
        app: withdraw-service
    spec:
      containers:
      - name: withdraw-service
        image: withdraw-service:1.0
        ports:
        - containerPort: 50060
        - containerPort: 8090
        envFrom:
        - configMapRef:
            name: app-config