apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: payment-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        ports:
        - containerPort: 2181
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - echo stat | nc localhost 2181
          initialDelaySeconds: 5
          periodSeconds: 5
