// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: card/stats/card_stats_transfer.proto

package stats

import (
	card "github.com/MamangRust/monolith-payment-gateway-pb/card"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_card_stats_card_stats_transfer_proto protoreflect.FileDescriptor

const file_card_stats_card_stats_transfer_proto_rawDesc = "" +
	"\n" +
	"$card/stats/card_stats_transfer.proto\x12\rpb.card.stats\x1a\x0fcard/card.proto2\xfa\x06\n" +
	"\x18CardStatsTransferService\x12_\n" +
	"\x1fFindMonthlyTransferSenderAmount\x12\x17.pb.card.FindYearAmount\x1a!.pb.card.ApiResponseMonthlyAmount\"\x00\x12]\n" +
	"\x1eFindYearlyTransferSenderAmount\x12\x17.pb.card.FindYearAmount\x1a .pb.card.ApiResponseYearlyAmount\"\x00\x12a\n" +
	"!FindMonthlyTransferReceiverAmount\x12\x17.pb.card.FindYearAmount\x1a!.pb.card.ApiResponseMonthlyAmount\"\x00\x12_\n" +
	" FindYearlyTransferReceiverAmount\x12\x17.pb.card.FindYearAmount\x1a .pb.card.ApiResponseYearlyAmount\"\x00\x12u\n" +
	"+FindMonthlyTransferSenderAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a!.pb.card.ApiResponseMonthlyAmount\"\x00\x12s\n" +
	"*FindYearlyTransferSenderAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a .pb.card.ApiResponseYearlyAmount\"\x00\x12w\n" +
	"-FindMonthlyTransferReceiverAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a!.pb.card.ApiResponseMonthlyAmount\"\x00\x12u\n" +
	",FindYearlyTransferReceiverAmountByCardNumber\x12!.pb.card.FindYearAmountCardNumber\x1a .pb.card.ApiResponseYearlyAmount\"\x00B>Z<github.com/MamangRust/monolith-payment-gateway-pb/card/statsb\x06proto3"

var file_card_stats_card_stats_transfer_proto_goTypes = []any{
	(*card.FindYearAmount)(nil),           // 0: pb.card.FindYearAmount
	(*card.FindYearAmountCardNumber)(nil), // 1: pb.card.FindYearAmountCardNumber
	(*card.ApiResponseMonthlyAmount)(nil), // 2: pb.card.ApiResponseMonthlyAmount
	(*card.ApiResponseYearlyAmount)(nil),  // 3: pb.card.ApiResponseYearlyAmount
}
var file_card_stats_card_stats_transfer_proto_depIdxs = []int32{
	0, // 0: pb.card.stats.CardStatsTransferService.FindMonthlyTransferSenderAmount:input_type -> pb.card.FindYearAmount
	0, // 1: pb.card.stats.CardStatsTransferService.FindYearlyTransferSenderAmount:input_type -> pb.card.FindYearAmount
	0, // 2: pb.card.stats.CardStatsTransferService.FindMonthlyTransferReceiverAmount:input_type -> pb.card.FindYearAmount
	0, // 3: pb.card.stats.CardStatsTransferService.FindYearlyTransferReceiverAmount:input_type -> pb.card.FindYearAmount
	1, // 4: pb.card.stats.CardStatsTransferService.FindMonthlyTransferSenderAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	1, // 5: pb.card.stats.CardStatsTransferService.FindYearlyTransferSenderAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	1, // 6: pb.card.stats.CardStatsTransferService.FindMonthlyTransferReceiverAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	1, // 7: pb.card.stats.CardStatsTransferService.FindYearlyTransferReceiverAmountByCardNumber:input_type -> pb.card.FindYearAmountCardNumber
	2, // 8: pb.card.stats.CardStatsTransferService.FindMonthlyTransferSenderAmount:output_type -> pb.card.ApiResponseMonthlyAmount
	3, // 9: pb.card.stats.CardStatsTransferService.FindYearlyTransferSenderAmount:output_type -> pb.card.ApiResponseYearlyAmount
	2, // 10: pb.card.stats.CardStatsTransferService.FindMonthlyTransferReceiverAmount:output_type -> pb.card.ApiResponseMonthlyAmount
	3, // 11: pb.card.stats.CardStatsTransferService.FindYearlyTransferReceiverAmount:output_type -> pb.card.ApiResponseYearlyAmount
	2, // 12: pb.card.stats.CardStatsTransferService.FindMonthlyTransferSenderAmountByCardNumber:output_type -> pb.card.ApiResponseMonthlyAmount
	3, // 13: pb.card.stats.CardStatsTransferService.FindYearlyTransferSenderAmountByCardNumber:output_type -> pb.card.ApiResponseYearlyAmount
	2, // 14: pb.card.stats.CardStatsTransferService.FindMonthlyTransferReceiverAmountByCardNumber:output_type -> pb.card.ApiResponseMonthlyAmount
	3, // 15: pb.card.stats.CardStatsTransferService.FindYearlyTransferReceiverAmountByCardNumber:output_type -> pb.card.ApiResponseYearlyAmount
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_card_stats_card_stats_transfer_proto_init() }
func file_card_stats_card_stats_transfer_proto_init() {
	if File_card_stats_card_stats_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_stats_card_stats_transfer_proto_rawDesc), len(file_card_stats_card_stats_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_stats_card_stats_transfer_proto_goTypes,
		DependencyIndexes: file_card_stats_card_stats_transfer_proto_depIdxs,
	}.Build()
	File_card_stats_card_stats_transfer_proto = out.File
	file_card_stats_card_stats_transfer_proto_goTypes = nil
	file_card_stats_card_stats_transfer_proto_depIdxs = nil
}
