name: Build and push

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [apigateway, auth, user, role, card, merchant, saldo, topup, transaction, transfer, withdraw, email, migrate]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mamangrust/monolith-payment-gateway-grpc/${{ matrix.service }}
          tags: |
            type=ref,event=branch,name=main
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=${{ matrix.service }}
            org.opencontainers.image.description=Microservice ${{ matrix.service }} for Payment Gateway
            org.opencontainers.image.source=https://github.com/mamangrust/monolith-payment-gateway-grpc
            org.opencontainers.image.url=https://github.com/mamangrust/monolith-payment-gateway-grpc
            org.opencontainers.image.licenses=MIT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MY_TOKEN }}

      - name: Debug Build Info
        run: |
          echo "Building service: ${{ matrix.service }}"
          echo "Dockerfile: service/${{ matrix.service }}/Dockerfile"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./service/${{ matrix.service }}
          file: ./service/${{ matrix.service }}/Dockerfile
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/mamangrust/monolith-payment-gateway-grpc/${{ matrix.service }}:latest
          labels: ${{ steps.meta.outputs.labels }}
