// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: card/card.proto

package card

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllCardRequest) Reset() {
	*x = FindAllCardRequest{}
	mi := &file_card_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllCardRequest) ProtoMessage() {}

func (x *FindAllCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllCardRequest.ProtoReflect.Descriptor instead.
func (*FindAllCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllCardRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllCardRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllCardRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByCardNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByCardNumberRequest) Reset() {
	*x = FindByCardNumberRequest{}
	mi := &file_card_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByCardNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByCardNumberRequest) ProtoMessage() {}

func (x *FindByCardNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByCardNumberRequest.ProtoReflect.Descriptor instead.
func (*FindByCardNumberRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{1}
}

func (x *FindByCardNumberRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type FindByUserIdCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByUserIdCardRequest) Reset() {
	*x = FindByUserIdCardRequest{}
	mi := &file_card_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByUserIdCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByUserIdCardRequest) ProtoMessage() {}

func (x *FindByUserIdCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByUserIdCardRequest.ProtoReflect.Descriptor instead.
func (*FindByUserIdCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{2}
}

func (x *FindByUserIdCardRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type FindByIdCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardId        int32                  `protobuf:"varint,1,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdCardRequest) Reset() {
	*x = FindByIdCardRequest{}
	mi := &file_card_card_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdCardRequest) ProtoMessage() {}

func (x *FindByIdCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdCardRequest.ProtoReflect.Descriptor instead.
func (*FindByIdCardRequest) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{3}
}

func (x *FindByIdCardRequest) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

type FindYearAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearAmount) Reset() {
	*x = FindYearAmount{}
	mi := &file_card_card_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearAmount) ProtoMessage() {}

func (x *FindYearAmount) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearAmount.ProtoReflect.Descriptor instead.
func (*FindYearAmount) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{4}
}

func (x *FindYearAmount) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearAmountCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	CardNumber    string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearAmountCardNumber) Reset() {
	*x = FindYearAmountCardNumber{}
	mi := &file_card_card_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearAmountCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearAmountCardNumber) ProtoMessage() {}

func (x *FindYearAmountCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearAmountCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearAmountCardNumber) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{5}
}

func (x *FindYearAmountCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindYearAmountCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type CardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardNumber    string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	ExpireDate    string                 `protobuf:"bytes,5,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Cvv           string                 `protobuf:"bytes,6,opt,name=cvv,proto3" json:"cvv,omitempty"`
	CardProvider  string                 `protobuf:"bytes,7,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponse) Reset() {
	*x = CardResponse{}
	mi := &file_card_card_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponse) ProtoMessage() {}

func (x *CardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponse.ProtoReflect.Descriptor instead.
func (*CardResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{6}
}

func (x *CardResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CardResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardResponse) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *CardResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardResponse) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *CardResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CardResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CardWithEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CardNumber    string                 `protobuf:"bytes,4,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                 `protobuf:"bytes,5,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	ExpireDate    string                 `protobuf:"bytes,6,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Cvv           string                 `protobuf:"bytes,7,opt,name=cvv,proto3" json:"cvv,omitempty"`
	CardProvider  string                 `protobuf:"bytes,8,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardWithEmailResponse) Reset() {
	*x = CardWithEmailResponse{}
	mi := &file_card_card_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardWithEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardWithEmailResponse) ProtoMessage() {}

func (x *CardWithEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardWithEmailResponse.ProtoReflect.Descriptor instead.
func (*CardWithEmailResponse) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{7}
}

func (x *CardWithEmailResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardWithEmailResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CardWithEmailResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CardWithEmailResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardWithEmailResponse) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardWithEmailResponse) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *CardWithEmailResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardWithEmailResponse) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *CardWithEmailResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CardWithEmailResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CardResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardNumber    string                  `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	CardType      string                  `protobuf:"bytes,4,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	ExpireDate    string                  `protobuf:"bytes,5,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	Cvv           string                  `protobuf:"bytes,6,opt,name=cvv,proto3" json:"cvv,omitempty"`
	CardProvider  string                  `protobuf:"bytes,7,opt,name=card_provider,json=cardProvider,proto3" json:"card_provider,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponseDeleteAt) Reset() {
	*x = CardResponseDeleteAt{}
	mi := &file_card_card_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponseDeleteAt) ProtoMessage() {}

func (x *CardResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*CardResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{8}
}

func (x *CardResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CardResponseDeleteAt) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CardResponseDeleteAt) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CardResponseDeleteAt) GetCardType() string {
	if x != nil {
		return x.CardType
	}
	return ""
}

func (x *CardResponseDeleteAt) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

func (x *CardResponseDeleteAt) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *CardResponseDeleteAt) GetCardProvider() string {
	if x != nil {
		return x.CardProvider
	}
	return ""
}

func (x *CardResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CardResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *CardResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CardResponse          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCard) Reset() {
	*x = ApiResponseCard{}
	mi := &file_card_card_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCard) ProtoMessage() {}

func (x *ApiResponseCard) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCard.ProtoReflect.Descriptor instead.
func (*ApiResponseCard) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponseCard) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCard) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCard) GetData() *CardResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseCardDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *CardResponseDeleteAt  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseCardDeleteAt) Reset() {
	*x = ApiResponseCardDeleteAt{}
	mi := &file_card_card_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseCardDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseCardDeleteAt) ProtoMessage() {}

func (x *ApiResponseCardDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseCardDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseCardDeleteAt) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{10}
}

func (x *ApiResponseCardDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseCardDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseCardDeleteAt) GetData() *CardResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type CardResponseMonthlyAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponseMonthlyAmount) Reset() {
	*x = CardResponseMonthlyAmount{}
	mi := &file_card_card_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponseMonthlyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponseMonthlyAmount) ProtoMessage() {}

func (x *CardResponseMonthlyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponseMonthlyAmount.ProtoReflect.Descriptor instead.
func (*CardResponseMonthlyAmount) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{11}
}

func (x *CardResponseMonthlyAmount) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *CardResponseMonthlyAmount) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CardResponseYearlyAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   int64                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardResponseYearlyAmount) Reset() {
	*x = CardResponseYearlyAmount{}
	mi := &file_card_card_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardResponseYearlyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardResponseYearlyAmount) ProtoMessage() {}

func (x *CardResponseYearlyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardResponseYearlyAmount.ProtoReflect.Descriptor instead.
func (*CardResponseYearlyAmount) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{12}
}

func (x *CardResponseYearlyAmount) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CardResponseYearlyAmount) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseMonthlyAmount struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        string                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CardResponseMonthlyAmount `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseMonthlyAmount) Reset() {
	*x = ApiResponseMonthlyAmount{}
	mi := &file_card_card_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseMonthlyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseMonthlyAmount) ProtoMessage() {}

func (x *ApiResponseMonthlyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseMonthlyAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseMonthlyAmount) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{13}
}

func (x *ApiResponseMonthlyAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseMonthlyAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseMonthlyAmount) GetData() []*CardResponseMonthlyAmount {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseYearlyAmount struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        string                      `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*CardResponseYearlyAmount `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseYearlyAmount) Reset() {
	*x = ApiResponseYearlyAmount{}
	mi := &file_card_card_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseYearlyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseYearlyAmount) ProtoMessage() {}

func (x *ApiResponseYearlyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_card_card_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseYearlyAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseYearlyAmount) Descriptor() ([]byte, []int) {
	return file_card_card_proto_rawDescGZIP(), []int{14}
}

func (x *ApiResponseYearlyAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseYearlyAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseYearlyAmount) GetData() []*CardResponseYearlyAmount {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_card_card_proto protoreflect.FileDescriptor

const file_card_card_proto_rawDesc = "" +
	"\n" +
	"\x0fcard/card.proto\x12\apb.card\x1a\x1egoogle/protobuf/wrappers.proto\"]\n" +
	"\x12FindAllCardRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\":\n" +
	"\x17FindByCardNumberRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\"2\n" +
	"\x17FindByUserIdCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\".\n" +
	"\x13FindByIdCardRequest\x12\x17\n" +
	"\acard_id\x18\x01 \x01(\x05R\x06cardId\"$\n" +
	"\x0eFindYearAmount\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"O\n" +
	"\x18FindYearAmountCardNumber\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\"\x8b\x02\n" +
	"\fCardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vexpire_date\x18\x05 \x01(\tR\n" +
	"expireDate\x12\x10\n" +
	"\x03cvv\x18\x06 \x01(\tR\x03cvv\x12#\n" +
	"\rcard_provider\x18\a \x01(\tR\fcardProvider\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xaa\x02\n" +
	"\x15CardWithEmailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vcard_number\x18\x04 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x05 \x01(\tR\bcardType\x12\x1f\n" +
	"\vexpire_date\x18\x06 \x01(\tR\n" +
	"expireDate\x12\x10\n" +
	"\x03cvv\x18\a \x01(\tR\x03cvv\x12#\n" +
	"\rcard_provider\x18\b \x01(\tR\fcardProvider\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xd0\x02\n" +
	"\x14CardResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x1b\n" +
	"\tcard_type\x18\x04 \x01(\tR\bcardType\x12\x1f\n" +
	"\vexpire_date\x18\x05 \x01(\tR\n" +
	"expireDate\x12\x10\n" +
	"\x03cvv\x18\x06 \x01(\tR\x03cvv\x12#\n" +
	"\rcard_provider\x18\a \x01(\tR\fcardProvider\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"n\n" +
	"\x0fApiResponseCard\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.pb.card.CardResponseR\x04data\"~\n" +
	"\x17ApiResponseCardDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.card.CardResponseDeleteAtR\x04data\"T\n" +
	"\x19CardResponseMonthlyAmount\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\"Q\n" +
	"\x18CardResponseYearlyAmount\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x03R\vtotalAmount\"\x84\x01\n" +
	"\x18ApiResponseMonthlyAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.card.CardResponseMonthlyAmountR\x04data\"\x82\x01\n" +
	"\x17ApiResponseYearlyAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.card.CardResponseYearlyAmountR\x04dataB8Z6github.com/MamangRust/monolith-payment-gateway-pb/cardb\x06proto3"

var (
	file_card_card_proto_rawDescOnce sync.Once
	file_card_card_proto_rawDescData []byte
)

func file_card_card_proto_rawDescGZIP() []byte {
	file_card_card_proto_rawDescOnce.Do(func() {
		file_card_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_card_proto_rawDesc), len(file_card_card_proto_rawDesc)))
	})
	return file_card_card_proto_rawDescData
}

var file_card_card_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_card_card_proto_goTypes = []any{
	(*FindAllCardRequest)(nil),        // 0: pb.card.FindAllCardRequest
	(*FindByCardNumberRequest)(nil),   // 1: pb.card.FindByCardNumberRequest
	(*FindByUserIdCardRequest)(nil),   // 2: pb.card.FindByUserIdCardRequest
	(*FindByIdCardRequest)(nil),       // 3: pb.card.FindByIdCardRequest
	(*FindYearAmount)(nil),            // 4: pb.card.FindYearAmount
	(*FindYearAmountCardNumber)(nil),  // 5: pb.card.FindYearAmountCardNumber
	(*CardResponse)(nil),              // 6: pb.card.CardResponse
	(*CardWithEmailResponse)(nil),     // 7: pb.card.CardWithEmailResponse
	(*CardResponseDeleteAt)(nil),      // 8: pb.card.CardResponseDeleteAt
	(*ApiResponseCard)(nil),           // 9: pb.card.ApiResponseCard
	(*ApiResponseCardDeleteAt)(nil),   // 10: pb.card.ApiResponseCardDeleteAt
	(*CardResponseMonthlyAmount)(nil), // 11: pb.card.CardResponseMonthlyAmount
	(*CardResponseYearlyAmount)(nil),  // 12: pb.card.CardResponseYearlyAmount
	(*ApiResponseMonthlyAmount)(nil),  // 13: pb.card.ApiResponseMonthlyAmount
	(*ApiResponseYearlyAmount)(nil),   // 14: pb.card.ApiResponseYearlyAmount
	(*wrapperspb.StringValue)(nil),    // 15: google.protobuf.StringValue
}
var file_card_card_proto_depIdxs = []int32{
	15, // 0: pb.card.CardResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	6,  // 1: pb.card.ApiResponseCard.data:type_name -> pb.card.CardResponse
	8,  // 2: pb.card.ApiResponseCardDeleteAt.data:type_name -> pb.card.CardResponseDeleteAt
	11, // 3: pb.card.ApiResponseMonthlyAmount.data:type_name -> pb.card.CardResponseMonthlyAmount
	12, // 4: pb.card.ApiResponseYearlyAmount.data:type_name -> pb.card.CardResponseYearlyAmount
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_card_card_proto_init() }
func file_card_card_proto_init() {
	if File_card_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_card_proto_rawDesc), len(file_card_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_card_proto_goTypes,
		DependencyIndexes: file_card_card_proto_depIdxs,
		MessageInfos:      file_card_card_proto_msgTypes,
	}.Build()
	File_card_card_proto = out.File
	file_card_card_proto_goTypes = nil
	file_card_card_proto_depIdxs = nil
}
